@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDM0NGRiM2MwMTgyYTZlODkxOGZlNDgiLCJ1c2VybmFtZSI6IlNhcmFoIG1pa2UiLCJwcm9maWxlUGljIjoiaHR0cHM6Ly9pbWFnZS5zaHV0dGVyc3RvY2suY29tL2ltYWdlLXBob3RvL3BvcnRyYWl0LXBvc2l0aXZlLXNraWxsZWQtYWZyby1hbWVyaWNhbi02MDB3LTE2OTIwNTY3OTEuanBnIiwiaWF0IjoxNjE2OTQ4MDIxfQ.rBn2TQzY3KQQ_Q38Ym2fyhprFwzTSOhhfBHqCVoaJyw

GET http://localhost:9090/users


###
POST http://localhost:9090/signup
Content-Type: application/json

{
   "username": "",
   "email": "mikeJohn@yahoo.com",
   "password": "123456",
   "confirmPassword": "123456"
}

###
POST http://localhost:9090/signin
Content-Type: application/json

{
   "email": "danabramov@gmail.com",
   "password": "123456"
}


### login
POST http://localhost:9090/login
Content-Type: application/json

{
   "identifier": "michael.tu@gmail.com",
   "password": "123456"
}


### Get User
GET http://localhost:9090/user
Content-Type: application/json
Authorization: Bearer {{token}}


#### Update user info
PUT http://localhost:9090/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "profilePic": "https://image.freepik.com/free-vector/cute-monkey-cartoon_146562-7.jpg"
}

###

POST http://localhost:9090/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "body": "Learn React is hard?"
}


### Get posts
GET http://localhost:9090/posts
Authorization: Bearer {{token}}


### Get Single Post
GET http://localhost:9090/post/6026fb5604640d0fcc8c1460
Authorization: Bearer {{token}}


### Create a reply
POST http://localhost:9090/reply/5ffcf68dbcf65b7c92d9b64b
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "body": "wowo that's awesame right there! good work"
}



### Get replies
GET http://localhost:9090/replies/5ffcf68dbcf65b7c92d9b64b
Content-Type: application/json
Authorization: Bearer {{token}}


### Create channels
POST http://localhost:9090/channels
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Nodejs"
}

### Get channels for specific user
GET http://localhost:9090/channels
Authorization: Bearer {{token}}


### Get single Channel info
GET http://localhost:9090/channels/60344f15c0182a6e8918fe4a
Authorization: Bearer {{token}}


### create message
post http://localhost:9090/messages/60344f15c0182a6e8918fe4a
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "body": "first message test for this channel"
}

### get all messages for a specific channel
GET http://localhost:9090/messages/60344f15c0182a6e8918fe4a
Authorization: Bearer {{token}}


### delete specific message
DELETE http://localhost:9090/messages/60460bd937b15579a452b32b
Authorization: Bearer {{token}}