@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDBiMTQzNTc3NDE0OTc1NzRkMWVjNzgiLCJ1c2VybmFtZSI6IkNoYXJsZXMiLCJlbWFpbCI6ImNoYXJsZXNAZ21haWwuY29tIiwiaWF0IjoxNjEzNjU0NjcwfQ.KmYW0B7UzCaA4MEM7MlvYiuwQJOyE3DlrREm64NzKrI

GET http://localhost:9090/users


###
POST http://localhost:9090/signup
Content-Type: application/json

{
   "username": "",
   "email": "mikeJohn@yahoo.com",
   "password": "123456",
   "confirmPassword": "123456"
}

###
POST http://localhost:9090/signin
Content-Type: application/json

{
   "email": "michael.tu@gmail.com",
   "password": "123456"
}


### login
POST http://localhost:9090/login
Content-Type: application/json

{
   "identifier": "michael.tu@gmail.com",
   "password": "123456"
}


### Get User
GET http://localhost:9090/user
Content-Type: application/json
Authorization: Bearer {{token}}


#### Update user info
PUT http://localhost:9090/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "profilePic": "https://image.freepik.com/free-vector/cute-monkey-cartoon_146562-7.jpg"
}

###

POST http://localhost:9090/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "body": "Learn React is hard?"
}


### Get posts
GET http://localhost:9090/posts
Authorization: Bearer {{token}}



### Get Single Post
GET http://localhost:9090/post/6026fb5604640d0fcc8c1460
Authorization: Bearer {{token}}


### Create a reply
POST http://localhost:9090/reply/5ffcf68dbcf65b7c92d9b64b
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "body": "wowo that's awesame right there! good work"
}



### Get replies
GET http://localhost:9090/replies/5ffcf68dbcf65b7c92d9b64b
Content-Type: application/json
Authorization: Bearer {{token}}


### Create channels
POST http://localhost:9090/channels
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Nodejs"
}

### Get channels for specific user
GET http://localhost:9090/channels
Authorization: Bearer {{token}}