-- SQL STATEMENT FOR CREATING USER TABLE
CREATE TABLE User (
  id UNIQUE INTEGER NOT NULL,
  handle VARCHAR(30) NOT NULL,
  email UNIQUE VARCHAR(255) NOT NULL,
  [status] VARCHAR(7) NOT NULL,
  [password] VARCHAR(255) NOT NULL,
  created_At DATE/TIME NOT NULL,
  updated_At DATE/TIME NOT NULL,
  reset_Password_Token VARCHAR(255) NOT NULL,
  reset_Password_Expires DATE/TIME NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE Credentail (
  id UNIQUE INTEGER NOT NULL,
  bio VARCHAR NULL,
  PRIMARY KEY ("id"),
  profile_Pic VARCHAR(255) NOT NULL,
)

-- SQL STATEMENT FOR CREATING CHANNEL TABLE
CREATE TABLE Channel (
  id UNIQUE INTEGER NOT NULL,
  [name] VARCHAR(30) NOT NULL,
  [user_Id] UNIQUE INTEGER NOT NULL,
  [description] VARCHAR(255) NOT NULL,
  [identifier]: INTEGER NOT NULL, 
  visibility VARCHAR(7) NOT NULL,
  created_At DATE/TIME NOT NULL,
  updated_At DATE/TIME NOT NULL,
  PRIMARY KEY ("id")
);

-- SQL STATEMENT FOR CREATING MESSAGE TABLE
CREATE TABLE Message (
  id UNIQUE INTEGER NOT NULL,
  channel_Id INTEGER NOT NULL,
  [user_Id] INTEGER NOT NULL,
  body VARCHAR NOT NULL,
  created_At DATE/TIME NOT NULL,
  updated_At DATE/TIME NOT NULL,
  PRIMARY KEY ("id")
);

-- SQL STATEMENT FOR CREATING MEMBER TABLE
CREATE TABLE Member (
  id UNIQUE INTEGER NOT NULL,
  channel_I UNIQUE VARCHAR(255) NOT NULL,
  [user_Id] UNIQUE VARCHAR(255) NOT NULL,
  created_At DATE/TIME NOT NULL,
  PRIMARY KEY ("id")
);

